import { Product, Category } from './types';

export const CATEGORIES: Category[] = [
  { id: 'surgery', name: 'Chirurgie', icon: 'Scissors' },
  { id: 'ortho', name: 'Orthopédie', icon: 'Bone' },
  { id: 'cardio', name: 'Cardiologie', icon: 'HeartPulse' },
  { id: 'radiology', name: 'Radiologie', icon: 'Scan' },
  { id: 'gyn', name: 'Gynécologie', icon: 'Baby' },
  { id: 'emergency', name: 'Urgences', icon: 'Stethoscope' },
  { id: 'general', name: 'Général', icon: 'ClipboardList' },
];

export const PRODUCTS: Product[] = [
  // --- CHIRURGIE (15) ---
  {
    id: 's1',
    name: 'Sutures Vicryl 3-0',
    category: 'surgery',
    price: 495.0,
    stockStatus: 'high',
    stockCount: 150,
    dlc: '2027-12-31',
    manufacturer: 'Ethicon',
    image: 'https://picsum.photos/seed/suture1/400/400',
    isReimbursed: true,
    description: 'Suture synthétique résorbable tressée, enduite, composée d\'un copolymère de glycolide et de lactide.',
  },
  {
    id: 's2',
    name: 'Gants Stériles Latex T8',
    category: 'surgery',
    price: 135.0,
    stockStatus: 'low',
    stockCount: 15,
    dlc: '2026-05-15',
    manufacturer: 'Ansell',
    image: 'https://picsum.photos/seed/gloves1/400/400',
    isReimbursed: false,
    description: 'Gants de chirurgie en latex, sans poudre, offrant une sensibilité tactile exceptionnelle.',
  },
  {
    id: 's3',
    name: 'Lames de Bistouri n°11',
    category: 'surgery',
    price: 220.0,
    stockStatus: 'high',
    stockCount: 500,
    dlc: '2028-10-20',
    manufacturer: 'Swann-Morton',
    image: 'https://picsum.photos/seed/blade1/400/400',
    isReimbursed: true,
    description: 'Lames de scalpel en acier au carbone, stériles, pour incisions précises.',
  },
  {
    id: 's4',
    name: 'Champs Opératoires 75x90',
    category: 'surgery',
    price: 385.0,
    stockStatus: 'medium',
    stockCount: 40,
    dlc: '2027-08-20',
    manufacturer: 'Hartmann',
    image: 'https://picsum.photos/seed/drape1/400/400',
    isReimbursed: true,
    description: 'Champ de soin imperméable et absorbant pour maintenir un champ stérile.',
  },
  {
    id: 's5',
    name: 'Drains Redon CH10',
    category: 'surgery',
    price: 310.0,
    stockStatus: 'high',
    stockCount: 80,
    dlc: '2028-01-01',
    manufacturer: 'B. Braun',
    image: 'https://picsum.photos/seed/drain1/400/400',
    isReimbursed: true,
    description: 'Système de drainage post-opératoire par aspiration.',
  },
  {
    id: 's6',
    name: 'Aspirateur de Fumée Chirurgicale',
    category: 'surgery',
    price: 1200.0,
    stockStatus: 'medium',
    stockCount: 10,
    dlc: '2030-01-01',
    manufacturer: 'Medtronic',
    image: 'https://picsum.photos/seed/smoke1/400/400',
    isReimbursed: true,
    description: 'Dispositif pour l\'évacuation des fumées lors des interventions au laser ou électrochirurgie.',
  },
  {
    id: 's7',
    name: 'Pince de DeBakey 20cm',
    category: 'surgery',
    price: 850.0,
    stockStatus: 'high',
    stockCount: 25,
    dlc: '2035-01-01',
    manufacturer: 'Aesculap',
    image: 'https://picsum.photos/seed/forceps1/400/400',
    isReimbursed: false,
    description: 'Pince atraumatique pour la manipulation des tissus délicats.',
  },
  {
    id: 's8',
    name: 'Porte-aiguille Mayo-Hegar',
    category: 'surgery',
    price: 720.0,
    stockStatus: 'medium',
    stockCount: 15,
    dlc: '2035-01-01',
    manufacturer: 'Aesculap',
    image: 'https://picsum.photos/seed/needleholder1/400/400',
    isReimbursed: false,
    description: 'Instrument chirurgical pour maintenir l\'aiguille lors des sutures.',
  },
  {
    id: 's9',
    name: 'Agrafeuse Cutanée 35W',
    category: 'surgery',
    price: 450.0,
    stockStatus: 'high',
    stockCount: 100,
    dlc: '2027-06-15',
    manufacturer: '3M',
    image: 'https://picsum.photos/seed/stapler1/400/400',
    isReimbursed: true,
    description: 'Agrafeuse cutanée jetable pour une fermeture rapide des plaies.',
  },
  {
    id: 's10',
    name: 'Colle Chirurgicale Dermabond',
    category: 'surgery',
    price: 980.0,
    stockStatus: 'low',
    stockCount: 8,
    dlc: '2026-12-01',
    manufacturer: 'Ethicon',
    image: 'https://picsum.photos/seed/glue1/400/400',
    isReimbursed: true,
    description: 'Adhésif cutané topique pour la fermeture des incisions chirurgicales.',
  },
  {
    id: 's11',
    name: 'Canule d\'Aspiration Yankauer',
    category: 'surgery',
    price: 45.0,
    stockStatus: 'high',
    stockCount: 300,
    dlc: '2028-03-10',
    manufacturer: 'Covidien',
    image: 'https://picsum.photos/seed/yankauer1/400/400',
    isReimbursed: true,
    description: 'Instrument d\'aspiration orale pour éliminer les fluides pendant la chirurgie.',
  },
  {
    id: 's12',
    name: 'Sondes Gastriques CH14',
    category: 'surgery',
    price: 65.0,
    stockStatus: 'medium',
    stockCount: 120,
    dlc: '2027-11-20',
    manufacturer: 'Vygon',
    image: 'https://picsum.photos/seed/probe1/400/400',
    isReimbursed: true,
    description: 'Sonde nasogastrique pour aspiration ou alimentation.',
  },
  {
    id: 's13',
    name: 'Filet de Hernie 15x15cm',
    category: 'surgery',
    price: 1550.0,
    stockStatus: 'medium',
    stockCount: 20,
    dlc: '2029-05-05',
    manufacturer: 'Bard',
    image: 'https://picsum.photos/seed/mesh1/400/400',
    isReimbursed: true,
    description: 'Plaque de renfort pour la cure de hernie inguinale.',
  },
  {
    id: 's14',
    name: 'Ciment Orthopédique 40g',
    category: 'surgery',
    price: 1100.0,
    stockStatus: 'high',
    stockCount: 35,
    dlc: '2027-02-28',
    manufacturer: 'Stryker',
    image: 'https://picsum.photos/seed/cement1/400/400',
    isReimbursed: true,
    description: 'Ciment osseux pour la fixation des prothèses articulaires.',
  },
  {
    id: 's15',
    name: 'Garrot Pneumatique Automatique',
    category: 'surgery',
    price: 8500.0,
    stockStatus: 'low',
    stockCount: 2,
    dlc: '2035-01-01',
    manufacturer: 'Zimmer',
    image: 'https://picsum.photos/seed/tourniquet1/400/400',
    isReimbursed: false,
    description: 'Système de garrot pour créer un champ opératoire exsangue.',
  },

  // --- ORTHOPÉDIE (10) ---
  {
    id: 'o1',
    name: 'Prothèse de Hanche Titane',
    category: 'ortho',
    price: 38500.0,
    stockStatus: 'medium',
    stockCount: 8,
    dlc: '2035-01-01',
    manufacturer: 'Zimmer Biomet',
    image: 'https://picsum.photos/seed/hip1/400/400',
    isReimbursed: true,
    description: 'Système de prothèse totale de hanche en alliage de titane.',
  },
  {
    id: 'o2',
    name: 'Attelle de Genou Articulée',
    category: 'ortho',
    price: 1250.0,
    stockStatus: 'high',
    stockCount: 25,
    dlc: '2030-01-01',
    manufacturer: 'DonJoy',
    image: 'https://picsum.photos/seed/knee1/400/400',
    isReimbursed: true,
    description: 'Orthèse de genou pour stabilisation post-opératoire.',
  },
  {
    id: 'o3',
    name: 'Bandes Plâtrées 15cm x 3m',
    category: 'ortho',
    price: 45.0,
    stockStatus: 'high',
    stockCount: 200,
    dlc: '2028-06-30',
    manufacturer: 'BSN Medical',
    image: 'https://picsum.photos/seed/plaster1/400/400',
    isReimbursed: true,
    description: 'Bandes de plâtre à prise rapide pour immobilisation.',
  },
  {
    id: 'o4',
    name: 'Vis d\'Ostéosynthèse 3.5mm',
    category: 'ortho',
    price: 320.0,
    stockStatus: 'high',
    stockCount: 150,
    dlc: '2035-01-01',
    manufacturer: 'Synthes',
    image: 'https://picsum.photos/seed/screw1/400/400',
    isReimbursed: true,
    description: 'Vis corticale en acier inoxydable pour fixation osseuse.',
  },
  {
    id: 'o5',
    name: 'Plaque de Compression DCP',
    category: 'ortho',
    price: 2450.0,
    stockStatus: 'medium',
    stockCount: 12,
    dlc: '2035-01-01',
    manufacturer: 'Synthes',
    image: 'https://picsum.photos/seed/plate1/400/400',
    isReimbursed: true,
    description: 'Plaque pour le traitement des fractures des os longs.',
  },
  {
    id: 'o6',
    name: 'Botte de Marche Maxtrax',
    category: 'ortho',
    price: 1850.0,
    stockStatus: 'high',
    stockCount: 15,
    dlc: '2030-01-01',
    manufacturer: 'DonJoy',
    image: 'https://picsum.photos/seed/boot1/400/400',
    isReimbursed: true,
    description: 'Botte d\'immobilisation pour fractures de la cheville.',
  },
  {
    id: 'o7',
    name: 'Collier Cervical Philadelphia',
    category: 'ortho',
    price: 450.0,
    stockStatus: 'medium',
    stockCount: 30,
    dlc: '2029-12-31',
    manufacturer: 'Össur',
    image: 'https://picsum.photos/seed/collar1/400/400',
    isReimbursed: true,
    description: 'Collier cervical rigide pour traumatisme rachidien.',
  },
  {
    id: 'o8',
    name: 'Fixateur Externe de Poignet',
    category: 'ortho',
    price: 12000.0,
    stockStatus: 'low',
    stockCount: 3,
    dlc: '2035-01-01',
    manufacturer: 'Stryker',
    image: 'https://picsum.photos/seed/fixator1/400/400',
    isReimbursed: true,
    description: 'Système de fixation externe pour fractures complexes du poignet.',
  },
  {
    id: 'o9',
    name: 'Écharpe de Bras Universelle',
    category: 'ortho',
    price: 120.0,
    stockStatus: 'high',
    stockCount: 100,
    dlc: '2030-01-01',
    manufacturer: 'Thuasne',
    image: 'https://picsum.photos/seed/sling1/400/400',
    isReimbursed: true,
    description: 'Dispositif de maintien pour le membre supérieur.',
  },
  {
    id: 'o10',
    name: 'Clou Gamma 3 Long',
    category: 'ortho',
    price: 8500.0,
    stockStatus: 'medium',
    stockCount: 5,
    dlc: '2035-01-01',
    manufacturer: 'Stryker',
    image: 'https://picsum.photos/seed/nail1/400/400',
    isReimbursed: true,
    description: 'Clou intramédullaire pour fractures du fémur.',
  },

  // --- CARDIOLOGIE (10) ---
  {
    id: 'c1',
    name: 'Stent Cardiaque Bio-résorbable',
    category: 'cardio',
    price: 13200.0,
    stockStatus: 'low',
    stockCount: 3,
    dlc: '2028-11-15',
    manufacturer: 'Abbott',
    image: 'https://picsum.photos/seed/stent1/400/400',
    isReimbursed: true,
    description: 'Stent de dernière génération pour angioplastie coronaire.',
  },
  {
    id: 'c2',
    name: 'Cathéter de Diagnostic 5F',
    category: 'cardio',
    price: 850.0,
    stockStatus: 'high',
    stockCount: 50,
    dlc: '2027-04-10',
    manufacturer: 'Terumo',
    image: 'https://picsum.photos/seed/catheter1/400/400',
    isReimbursed: true,
    description: 'Cathéter angiographique pour imagerie coronaire.',
  },
  {
    id: 'c3',
    name: 'Électrodes ECG Adhésives (x100)',
    category: 'cardio',
    price: 180.0,
    stockStatus: 'high',
    stockCount: 1000,
    dlc: '2028-01-01',
    manufacturer: '3M',
    image: 'https://picsum.photos/seed/ecg1/400/400',
    isReimbursed: true,
    description: 'Électrodes à usage unique pour monitorage cardiaque.',
  },
  {
    id: 'c4',
    name: 'Guide Coronaire 0.014"',
    category: 'cardio',
    price: 1100.0,
    stockStatus: 'medium',
    stockCount: 40,
    dlc: '2027-09-15',
    manufacturer: 'Boston Scientific',
    image: 'https://picsum.photos/seed/guide1/400/400',
    isReimbursed: true,
    description: 'Fil guide pour navigation dans les artères coronaires.',
  },
  {
    id: 'c5',
    name: 'Ballon d\'Angioplastie NC',
    category: 'cardio',
    price: 2800.0,
    stockStatus: 'medium',
    stockCount: 20,
    dlc: '2027-12-31',
    manufacturer: 'Medtronic',
    image: 'https://picsum.photos/seed/balloon1/400/400',
    isReimbursed: true,
    description: 'Ballon de dilatation non-compliant pour angioplastie.',
  },
  {
    id: 'c6',
    name: 'Introducteur Radial 6F',
    category: 'cardio',
    price: 450.0,
    stockStatus: 'high',
    stockCount: 60,
    dlc: '2028-05-20',
    manufacturer: 'Terumo',
    image: 'https://picsum.photos/seed/sheath1/400/400',
    isReimbursed: true,
    description: 'Kit d\'introduction pour accès artériel radial.',
  },
  {
    id: 'c7',
    name: 'Pacemaker Double Chambre',
    category: 'cardio',
    price: 25000.0,
    stockStatus: 'low',
    stockCount: 2,
    dlc: '2030-01-01',
    manufacturer: 'Biotronik',
    image: 'https://picsum.photos/seed/pacemaker1/400/400',
    isReimbursed: true,
    description: 'Stimulateur cardiaque implantable haute performance.',
  },
  {
    id: 'c8',
    name: 'Sonde de Défibrillation',
    category: 'cardio',
    price: 18000.0,
    stockStatus: 'low',
    stockCount: 2,
    dlc: '2030-01-01',
    manufacturer: 'Medtronic',
    image: 'https://picsum.photos/seed/lead2/400/400',
    isReimbursed: true,
    description: 'Sonde endocavitaire pour défibrillateur implantable.',
  },
  {
    id: 'c9',
    name: 'Gel Conducteur ECG 250ml',
    category: 'cardio',
    price: 35.0,
    stockStatus: 'high',
    stockCount: 150,
    dlc: '2029-01-01',
    manufacturer: 'Parker',
    image: 'https://picsum.photos/seed/gel1/400/400',
    isReimbursed: true,
    description: 'Gel de contact pour examens ECG et ultrasons.',
  },
  {
    id: 'c10',
    name: 'Valve Cardiaque Biologique',
    category: 'cardio',
    price: 45000.0,
    stockStatus: 'low',
    stockCount: 1,
    dlc: '2030-01-01',
    manufacturer: 'Edwards',
    image: 'https://picsum.photos/seed/valve1/400/400',
    isReimbursed: true,
    description: 'Bioprothèse valvulaire pour remplacement aortique.',
  },

  // --- RADIOLOGIE (10) ---
  {
    id: 'r1',
    name: 'Produit de Contraste Ioméron',
    category: 'radiology',
    price: 935.0,
    stockStatus: 'medium',
    stockCount: 45,
    dlc: '2026-04-10',
    manufacturer: 'Bracco',
    image: 'https://picsum.photos/seed/contrast1/400/400',
    isReimbursed: true,
    description: 'Agent de contraste non ionique pour examen radiologique.',
  },
  {
    id: 'r2',
    name: 'Protection Plombée 0.5mm',
    category: 'radiology',
    price: 2695.0,
    stockStatus: 'low',
    stockCount: 5,
    dlc: '2030-01-01',
    manufacturer: 'Mavig',
    image: 'https://picsum.photos/seed/lead1/400/400',
    isReimbursed: false,
    description: 'Tablier de protection contre les rayons X.',
  },
  {
    id: 'r3',
    name: 'Films Radiographiques 35x43',
    category: 'radiology',
    price: 1850.0,
    stockStatus: 'medium',
    stockCount: 20,
    dlc: '2028-01-01',
    manufacturer: 'Fujifilm',
    image: 'https://picsum.photos/seed/film1/400/400',
    isReimbursed: true,
    description: 'Films pour imagerie médicale conventionnelle.',
  },
  {
    id: 'r4',
    name: 'Gel Échographie 5L',
    category: 'radiology',
    price: 120.0,
    stockStatus: 'high',
    stockCount: 100,
    dlc: '2029-06-30',
    manufacturer: 'Parker',
    image: 'https://picsum.photos/seed/gel2/400/400',
    isReimbursed: true,
    description: 'Gel de transmission pour examens échographiques.',
  },
  {
    id: 'r5',
    name: 'Aiguille de Biopsie Coaxiale',
    category: 'radiology',
    price: 650.0,
    stockStatus: 'medium',
    stockCount: 30,
    dlc: '2027-10-15',
    manufacturer: 'Bard',
    image: 'https://picsum.photos/seed/biopsy1/400/400',
    isReimbursed: true,
    description: 'Dispositif pour prélèvement tissulaire sous guidage imagerie.',
  },
  {
    id: 'r6',
    name: 'Protection Thyroïdienne',
    category: 'radiology',
    price: 450.0,
    stockStatus: 'high',
    stockCount: 15,
    dlc: '2035-01-01',
    manufacturer: 'Mavig',
    image: 'https://picsum.photos/seed/thyroid1/400/400',
    isReimbursed: false,
    description: 'Collier plombé pour protection de la thyroïde.',
  },
  {
    id: 'r7',
    name: 'Marqueur de Peau Radiologique',
    category: 'radiology',
    price: 85.0,
    stockStatus: 'high',
    stockCount: 200,
    dlc: '2030-01-01',
    manufacturer: 'Beekley',
    image: 'https://picsum.photos/seed/marker1/400/400',
    isReimbursed: false,
    description: 'Marqueurs adhésifs pour repérage en mammographie.',
  },
  {
    id: 'r8',
    name: 'Seringue Injecteur CT 200ml',
    category: 'radiology',
    price: 320.0,
    stockStatus: 'high',
    stockCount: 80,
    dlc: '2028-05-10',
    manufacturer: 'Medrad',
    image: 'https://picsum.photos/seed/injector1/400/400',
    isReimbursed: true,
    description: 'Seringue haute pression pour injecteur automatique de contraste.',
  },
  {
    id: 'r9',
    name: 'Gants Plombés de Protection',
    category: 'radiology',
    price: 1550.0,
    stockStatus: 'medium',
    stockCount: 10,
    dlc: '2030-01-01',
    manufacturer: 'Mavig',
    image: 'https://picsum.photos/seed/leadgloves1/400/400',
    isReimbursed: false,
    description: 'Gants pour protection des mains lors d\'interventions radioguidées.',
  },
  {
    id: 'r10',
    name: 'Papier Imprimante Vidéo Sony',
    category: 'radiology',
    price: 250.0,
    stockStatus: 'high',
    stockCount: 50,
    dlc: '2030-01-01',
    manufacturer: 'Sony',
    image: 'https://picsum.photos/seed/paper1/400/400',
    isReimbursed: true,
    description: 'Papier thermique haute densité pour impression échographique.',
  },

  // --- GYNÉCOLOGIE (10) ---
  {
    id: 'g1',
    name: 'Spéculum Vaginal Jetable',
    category: 'gyn',
    price: 27.5,
    stockStatus: 'high',
    stockCount: 200,
    dlc: '2029-01-01',
    manufacturer: 'Welch Allyn',
    image: 'https://picsum.photos/seed/speculum1/400/400',
    isReimbursed: false,
    description: 'Spéculum à usage unique en plastique transparent.',
  },
  {
    id: 'g2',
    name: 'Sonde d\'Échographie Endovaginale',
    category: 'gyn',
    price: 45000.0,
    stockStatus: 'low',
    stockCount: 2,
    dlc: '2035-01-01',
    manufacturer: 'GE Healthcare',
    image: 'https://picsum.photos/seed/sonde1/400/400',
    isReimbursed: false,
    description: 'Sonde haute résolution pour examens gynécologiques.',
  },
  {
    id: 'g3',
    name: 'Kit de Pose de Stérilet',
    category: 'gyn',
    price: 185.0,
    stockStatus: 'high',
    stockCount: 50,
    dlc: '2028-12-31',
    manufacturer: 'Gyneas',
    image: 'https://picsum.photos/seed/kit1/400/400',
    isReimbursed: true,
    description: 'Set complet stérile pour l\'insertion de DIU.',
  },
  {
    id: 'g4',
    name: 'DIU au Cuivre (Stérilet)',
    category: 'gyn',
    price: 350.0,
    stockStatus: 'high',
    stockCount: 40,
    dlc: '2029-06-01',
    manufacturer: 'Bayer',
    image: 'https://picsum.photos/seed/diu1/400/400',
    isReimbursed: true,
    description: 'Dispositif intra-utérin contraceptif au cuivre.',
  },
  {
    id: 'g5',
    name: 'Brosse de Frottis Cervical',
    category: 'gyn',
    price: 12.0,
    stockStatus: 'high',
    stockCount: 500,
    dlc: '2028-05-15',
    manufacturer: 'Rovers',
    image: 'https://picsum.photos/seed/brush1/400/400',
    isReimbursed: true,
    description: 'Brosse pour prélèvement de cellules cervicales.',
  },
  {
    id: 'g6',
    name: 'Gel Lubrifiant Stérile 82g',
    category: 'gyn',
    price: 45.0,
    stockStatus: 'high',
    stockCount: 100,
    dlc: '2029-01-01',
    manufacturer: 'K-Y Jelly',
    image: 'https://picsum.photos/seed/lubricant1/400/400',
    isReimbursed: false,
    description: 'Gel lubrifiant hydrosoluble stérile.',
  },
  {
    id: 'g7',
    name: 'Pince de Pozzi 25cm',
    category: 'gyn',
    price: 650.0,
    stockStatus: 'medium',
    stockCount: 10,
    dlc: '2035-01-01',
    manufacturer: 'Aesculap',
    image: 'https://picsum.photos/seed/pozzi1/400/400',
    isReimbursed: false,
    description: 'Pince de préhension du col de l\'utérus.',
  },
  {
    id: 'g8',
    name: 'Hystéromètre à usage unique',
    category: 'gyn',
    price: 35.0,
    stockStatus: 'high',
    stockCount: 150,
    dlc: '2028-10-10',
    manufacturer: 'Gyneas',
    image: 'https://picsum.photos/seed/hystero1/400/400',
    isReimbursed: true,
    description: 'Instrument pour mesurer la profondeur de la cavité utérine.',
  },
  {
    id: 'g9',
    name: 'Protection de Sonde (x100)',
    category: 'gyn',
    price: 220.0,
    stockStatus: 'high',
    stockCount: 300,
    dlc: '2029-12-31',
    manufacturer: 'Parker',
    image: 'https://picsum.photos/seed/cover1/400/400',
    isReimbursed: true,
    description: 'Gaines de protection stériles pour sondes endovaginales.',
  },
  {
    id: 'g10',
    name: 'Test de Grossesse HCG (x25)',
    category: 'gyn',
    price: 450.0,
    stockStatus: 'medium',
    stockCount: 20,
    dlc: '2027-06-30',
    manufacturer: 'Clearblue',
    image: 'https://picsum.photos/seed/test1/400/400',
    isReimbursed: false,
    description: 'Tests rapides urinaires pour détection de grossesse.',
  },

  // --- URGENCES (5) ---
  {
    id: 'e1',
    name: 'Défibrillateur de Poche',
    category: 'emergency',
    price: 16500.0,
    stockStatus: 'medium',
    stockCount: 12,
    dlc: '2030-06-01',
    manufacturer: 'Zoll',
    image: 'https://picsum.photos/seed/aed1/400/400',
    isReimbursed: true,
    description: 'Défibrillateur automatisé externe (DAE) ultra-compact.',
  },
  {
    id: 'e2',
    name: 'Masque à Haute Concentration',
    category: 'emergency',
    price: 45.0,
    stockStatus: 'high',
    stockCount: 100,
    dlc: '2028-01-01',
    manufacturer: 'Intersurgical',
    image: 'https://picsum.photos/seed/mask1/400/400',
    isReimbursed: true,
    description: 'Masque à oxygène avec réservoir pour haute concentration.',
  },
  {
    id: 'e3',
    name: 'Insufflateur Manuel Ambu',
    category: 'emergency',
    price: 850.0,
    stockStatus: 'medium',
    stockCount: 15,
    dlc: '2030-01-01',
    manufacturer: 'Ambu',
    image: 'https://picsum.photos/seed/ambu1/400/400',
    isReimbursed: true,
    description: 'Ballon auto-remplisseur pour ventilation manuelle.',
  },
  {
    id: 'e4',
    name: 'Canule de Guedel (Set x6)',
    category: 'emergency',
    price: 120.0,
    stockStatus: 'high',
    stockCount: 50,
    dlc: '2030-01-01',
    manufacturer: 'VBM',
    image: 'https://picsum.photos/seed/guedel1/400/400',
    isReimbursed: true,
    description: 'Canules oropharyngées pour maintien des voies aériennes.',
  },
  {
    id: 'e5',
    name: 'Couverture de Survie',
    category: 'emergency',
    price: 15.0,
    stockStatus: 'high',
    stockCount: 500,
    dlc: '2035-01-01',
    manufacturer: 'Reliance',
    image: 'https://picsum.photos/seed/survival1/400/400',
    isReimbursed: false,
    description: 'Couverture isothermique pour protection contre le froid ou la chaleur.',
  },

  // --- GÉNÉRAL (10) ---
  {
    id: 'gen1',
    name: 'Seringues 10ml Luer Lock',
    category: 'general',
    price: 55.0,
    stockStatus: 'high',
    stockCount: 500,
    dlc: '2029-06-30',
    manufacturer: 'BD',
    image: 'https://picsum.photos/seed/syringe1/400/400',
    isReimbursed: true,
    description: 'Seringue 3 pièces stérile avec embout Luer-Lock.',
  },
  {
    id: 'gen2',
    name: 'Aiguilles Hypodermiques 21G',
    category: 'general',
    price: 35.0,
    stockStatus: 'high',
    stockCount: 1000,
    dlc: '2029-01-01',
    manufacturer: 'BD',
    image: 'https://picsum.photos/seed/needle1/400/400',
    isReimbursed: true,
    description: 'Aiguilles stériles à usage unique (vertes).',
  },
  {
    id: 'gen3',
    name: 'Alcool Isopropylique 70% 1L',
    category: 'general',
    price: 45.0,
    stockStatus: 'high',
    stockCount: 200,
    dlc: '2028-12-31',
    manufacturer: 'Cooper',
    image: 'https://picsum.photos/seed/alcohol1/400/400',
    isReimbursed: false,
    description: 'Solution désinfectante pour la peau et les surfaces.',
  },
  {
    id: 'gen4',
    name: 'Coton Cardé 500g',
    category: 'general',
    price: 35.0,
    stockStatus: 'high',
    stockCount: 150,
    dlc: '2030-01-01',
    manufacturer: 'Lohmann & Rauscher',
    image: 'https://picsum.photos/seed/cotton1/400/400',
    isReimbursed: false,
    description: 'Coton hydrophile pour soins et nettoyage.',
  },
  {
    id: 'gen5',
    name: 'Pansements Adhésifs (Boîte 100)',
    category: 'general',
    price: 65.0,
    stockStatus: 'high',
    stockCount: 300,
    dlc: '2029-01-01',
    manufacturer: 'Hansaplast',
    image: 'https://picsum.photos/seed/plaster2/400/400',
    isReimbursed: false,
    description: 'Pansements hypoallergéniques pour petites plaies.',
  },
  {
    id: 'gen6',
    name: 'Sparadrap Micropore 2.5cm',
    category: 'general',
    price: 25.0,
    stockStatus: 'high',
    stockCount: 400,
    dlc: '2029-01-01',
    manufacturer: '3M',
    image: 'https://picsum.photos/seed/tape1/400/400',
    isReimbursed: true,
    description: 'Ruban adhésif papier hypoallergénique.',
  },
  {
    id: 'gen7',
    name: 'Gants d\'Examen Nitrile (x100)',
    category: 'general',
    price: 95.0,
    stockStatus: 'high',
    stockCount: 1000,
    dlc: '2028-05-10',
    manufacturer: 'Aurelia',
    image: 'https://picsum.photos/seed/nitrile1/400/400',
    isReimbursed: false,
    description: 'Gants non stériles sans latex, haute résistance.',
  },
  {
    id: 'gen8',
    name: 'Masques Chirurgicaux Type IIR',
    category: 'general',
    price: 45.0,
    stockStatus: 'high',
    stockCount: 5000,
    dlc: '2028-01-01',
    manufacturer: 'Kolmi',
    image: 'https://picsum.photos/seed/mask2/400/400',
    isReimbursed: false,
    description: 'Masques de protection 3 plis, haute filtration.',
  },
  {
    id: 'gen9',
    name: 'Solution Hydroalcoolique 500ml',
    category: 'general',
    price: 40.0,
    stockStatus: 'high',
    stockCount: 200,
    dlc: '2028-01-01',
    manufacturer: 'Anios',
    image: 'https://picsum.photos/seed/gel3/400/400',
    isReimbursed: false,
    description: 'Gel désinfectant pour les mains sans rinçage.',
  },
  {
    id: 'gen10',
    name: 'Thermomètre Infrarouge',
    category: 'general',
    price: 450.0,
    stockStatus: 'medium',
    stockCount: 30,
    dlc: '2035-01-01',
    manufacturer: 'Braun',
    image: 'https://picsum.photos/seed/thermo1/400/400',
    isReimbursed: false,
    description: 'Thermomètre sans contact pour mesure rapide.',
  },
];

export interface SurgeryKit {
  id: string;
  name: string;
  description: string;
  price: number;
  products: string[]; // IDs of products included
  image: string;
}

export const SURGERY_KITS: SurgeryKit[] = [
  {
    id: 'kit-laparo',
    name: 'Pack Laparoscopie Standard',
    description: 'Kit complet optimisé par IA pour interventions laparoscopiques courantes.',
    price: 4500.0,
    products: ['s1', 's2', 's3', 's4', 's11'],
    image: 'https://picsum.photos/seed/kitlaparo/400/400'
  },
  {
    id: 'kit-suture',
    name: 'Pack Suture & Fermeture',
    description: 'Sélection IA des meilleures sutures et colles pour une cicatrisation optimale.',
    price: 2200.0,
    products: ['s1', 's9', 's10'],
    image: 'https://picsum.photos/seed/kitsuture/400/400'
  },
  {
    id: 'kit-ortho-minor',
    name: 'Pack Orthopédie Mineure',
    description: 'Kit essentiel pour petites interventions orthopédiques.',
    price: 3800.0,
    products: ['s1', 's2', 's7', 's8', 's14'],
    image: 'https://picsum.photos/seed/kitortho/400/400'
  }
];

